import os

# ─────────────────────────────────────────────
# Infrastructure (S3, MongoDB, Redis)
# ─────────────────────────────────────────────

S3_BUCKET = os.environ.get("S3_BUCKET", "doc-classification")
AWS_REGION = os.environ.get("AWS_REGION", "us-east-1")
MONGODB_URI = os.environ.get("MONGODB_URI", "mongodb://localhost:27017")
MONGODB_DB = os.environ.get("MONGODB_DB", "classification")
REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379/0")

# ─────────────────────────────────────────────
# SVM Classification
# ─────────────────────────────────────────────

# If SVM confidence is above this, skip the agent phase entirely
SVM_CONFIDENCE_THRESHOLD = float(os.environ.get("SVM_THRESHOLD", "0.85"))

# Path to trained model files (generated by train_svm.py)
SVM_MODEL_PATH = os.environ.get("SVM_MODEL_PATH", "ml_models/svm_model.pkl")
TFIDF_VECTORIZER_PATH = os.environ.get("TFIDF_PATH", "ml_models/tfidf_vec.pkl")

# ─────────────────────────────────────────────
# Page sampling (for large files)
# ─────────────────────────────────────────────

# For files with many pages, only process first N and last N
# Most classification markers (headers/footers) are on these pages
MAX_SAMPLE_PAGES = int(os.environ.get("MAX_SAMPLE_PAGES", "4"))  # first 2 + last 2
MAX_FILE_SIZE_MB = int(os.environ.get("MAX_FILE_SIZE_MB", "50"))

# ─────────────────────────────────────────────
# AutoGen Agents (Phase 2 — edge case refinement)
# ─────────────────────────────────────────────

AGENT_MODEL = os.environ.get("AGENT_MODEL", "claude-sonnet-4-20250514")
AGENT_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
AGENT_MAX_TOKENS = int(os.environ.get("AGENT_MAX_TOKENS", "512"))
AGENT_SNIPPET_LENGTH = int(os.environ.get("AGENT_SNIPPET_LENGTH", "3000"))

# ─────────────────────────────────────────────
# Keywords — used as FEATURES for the SVM, not as the classifier
# The SVM learns how to weight these; we just compute the scores
# ─────────────────────────────────────────────

INVOICE_KEYWORDS = {
    # High signal (3)
    "invoice": 3, "invoice#": 3, "invoice number": 3, "bill to": 3,
    "amount due": 3, "total due": 3, "remit to": 3, "remittance": 3,
    "purchase order": 3, "po number": 3, "voucher": 3,
    # Medium signal (2)
    "subtotal": 2, "tax amount": 2, "payment terms": 2, "due date": 2,
    "ship to": 2, "sold to": 2, "unit price": 2, "line item": 2,
    "account statement": 2, "statement date": 2, "amount paid": 2,
    "balance due": 2, "net amount": 2, "gross amount": 2,
    # Lower signal (1)
    "quantity": 1, "description": 1, "total": 1, "receipt": 1,
    "order": 1, "charge": 1, "credit": 1, "payment": 1,
    "petty cash": 2, "expense": 1, "vendor": 1,
}

PMS_KEYWORDS = {
    # Report titles (3)
    "daily flash report": 3, "manager report": 3, "managers report": 3,
    "daily closing report": 3, "dayend close": 3, "night audit": 3,
    "trial balance": 3, "hotel statistics": 3, "occupancy": 3,
    "ledger activity": 3, "hotel ledger": 3, "flash comparison": 3,
    "revenue summary": 3, "rate and market": 3, "finance management": 3,
    "daily activity": 3, "final audit": 3, "daily closeout": 3,
    "transaction closeout": 3, "comparison by date": 3,
    "daily revenue report": 3,
    # Hotel metrics (2)
    "revpar": 2, "adr": 2, "room sold": 2, "rooms sold": 2,
    "occupancy rate": 2, "room revenue": 2, "room charges": 2,
    "check-in": 2, "checkin": 2, "checkout": 2, "check-out": 2,
    "guest count": 2, "in-house": 2, "no show": 2,
    "room taxable": 2, "room non-taxable": 2, "incidentals": 2,
    "month to date": 2, "year to date": 2, "mtd": 2, "ytd": 2,
}

PAYROLL_KEYWORDS = {
    "payroll register": 3, "payroll report": 3, "pay stub": 3,
    "pay date": 3, "pay period": 3, "payroll summary": 3,
    "gross pay": 3, "net pay": 3, "earnings statement": 3,
    "withholding": 2, "federal income tax": 2, "fit": 1,
    "fica": 2, "medi": 1, "medicare": 2, "social security": 2,
    "futa": 2, "suta": 2, "direct deposit": 2,
    "overtime": 1, "regular pay": 2, "hourly rate": 2,
    "employee": 1, "employer": 1, "deduction": 1,
}


STR_KEYWORDS = {
    "star report": 3, "str report": 3, "star monthly": 3,
    "competitive set": 3, "comp set": 3, "index": 2,
    "market penetration": 3, "revenue generating": 2,
    "quality assurance": 2, "qa report": 2, "qa evaluation": 2,
}

# Lookup tables for tagging (used AFTER classification, not during)
PMS_SYSTEMS = {
    "opera": "Opera", "fosse": "Fosse", "synxis": "Synxis",
    "choice advantage": "Choice Advantage", "inn road": "INN ROAD",
    "room master": "Room Master", "stay notch": "StayNToch",
    "visual matrix": "Visual Matrix", "light speed": "LightSpeed",
    "cloud beds": "Cloudbeds", "auto clerk": "AutoClerk",
    "hotel key": "HotelKey", "msi": "MSI", "check inn": "CheckInn",
    "rdp": "RDP", "onq": "ONQ", "redistay": "Redistay",
    "anand": "Anand Systems", "infor hms": "Infor HMS",
}

PAYROLL_PROVIDERS = [
    "paychex", "adp", "trinet", "isolved", "robco", "gusto",
    "onpay", "palocity", "primepoint", "heartland", "lyonshr",
]